import Head from 'next/head';
import cx from 'classnames/bind';
import globalStyles from 'styles/globals.styled';
import styles from './App.styled';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={cx('view-container')}>
        <Component {...pageProps} />
      </main>

      <style jsx>{globalStyles}</style>
      <style jsx>{styles}</style>
    </>
  );
}

export default MyApp;
